Add docs update
rarible/protocol pull request #211
Opened 2021-12-16 20:04 UTC by kolberszymon

2021-12-20 19:44 UTC, evgenynacu requested changes

2021-12-20 19:44 UTC, evgenynacu commented on docs/overview/union-sdk.md
> +  amount: 1 // Number of NFTs to buy (to buy more than one it has to be ERC1155 token)
If we talk about etc standard, then we are tied to ethereum. But Union SDK works for other blockchains too. So probably it's better to rephrase

2021-12-20 19:44 UTC, evgenynacu commented on docs/overview/union-sdk.md
> +- ethCurrency: EthErc20AssetType
Here, we should mention other currencies too? Not only erc20?

2021-12-20 19:44 UTC, evgenynacu commented on docs/overview/union-sdk.md
> +On rinkeby it's 0xc778417e063141139fce010982780140aa0cd5ab which is not related to the protocol. It's just a WETH address.
Here weth contract is only an example. Other token contracts can be used too

2021-12-20 19:44 UTC, evgenynacu commented on docs/overview/union-sdk.md
> +Similarly to updating a sell order there is also a possibility to update a bid. These time there is no limitation to the price. It can be higher as well as lower from original bid order.
I think you are not correct here. Bid can be only higher than previous

2021-12-20 19:44 UTC, evgenynacu commented on docs/overview/union-sdk.md
> +const tokenId =
Usually tokenId is only a number. So I think here is better to name it itemId

2021-12-20 19:44 UTC, evgenynacu commented on docs/overview/union-sdk.md
> +  to: toUnionAddress("ETHEREUM:0x79Ea2d536b5b7144A3EabdC6A7E43130199291c0"),
Also, in case if nft is multiple, amount can be sent here

2021-12-20 19:44 UTC, evgenynacu commented on docs/union-sdk/api.md
> +https://api-reference.rarible.com/
That's old apidoc, deprecated. Plus it's ethereum API, not Union

2021-12-20 19:44 UTC, evgenynacu commented on docs/union-sdk/api.md
> +While changing environments, you would need to change endpoints accordingly, because different APIs function in different chains e.g. there're different endpoints for Rinkeby than for the Ropsten. SD
It's better to tell about different envs and tell what blockchain networks are indexed there

2021-12-20 19:44 UTC, evgenynacu commented on docs/union-sdk/nft.md
> +  lazyMint: true,
Probably we need to tell that lazy mint is not always available. This can be seen in prepare mint response. There is a flag if lazy mint is supported. Also there are other flags too.
For example, lazy mint is not supported on tezos or flow

2021-12-20 19:44 UTC, evgenynacu commented on docs/union-sdk/nft.md
> +const tokenId =
The same thing. tokenId usually is number only

2021-12-20 19:44 UTC, evgenynacu commented on docs/union-sdk/nft.md
> +If you want to prepare metadata for your token, before sending them to IPFS, you can use preprocess function.
We can tell what's the purpose here: we need to prepare metadata for different blockchains. That's why we need this preprocess

2021-12-20 20:08 UTC, eduardstal commented on docs/overview/union-sdk.md
> +Of course if you want to submit a transfer transaction, you have to be the owner of an NFT.
If you wish to transfer an NFT token from an address to another, you'd have to submit a transfer transaction which can only be done if you're the owner of that NFT.

2021-12-24 09:30 UTC, kolberszymon commented on docs/union-sdk/api.md
> +https://api-reference.rarible.com/
should I use this one https://api.rarible.org/v0.1/doc?

2021-12-24 09:38 UTC, kolberszymon commented on docs/overview/union-sdk.md
> +## Create a bid
I think we should stick to present simple here otherwise, we should also change all of the other verbs to present continous

2021-12-24 11:47 UTC, evgenynacu commented on docs/union-sdk/api.md
> +https://api-reference.rarible.com/
@kolberszymon yes

2022-01-05 14:28 UTC, merged